### ISSUE TITLE
Use more adaptable socket protocol

### ISSUE THREAD

**Issue by LordMZTE** [LGFae/swww#168]
Currently, swww communicates with the daemon by sending rkyv-serialized packets over a unix socket. This has the drawback that it's virtually impossible (or at least wildly unstable) to communicate to the daemon from any other language than rust due to the nature of the protocol. I'd like to implement a client for the swww socket protocol in my wallpaper randomizer, which is written in Zig. This would allow me to avoid spawning ~4 swww processes for querying information about monitors as well as setting a wallpaper on each of them.

I propose that we use a clearly documented protocol. Options include:
- writing a custom binary protocol
- using cbor
- using JSON (wouldn't recommend)

This would be greatly appreciated!

**Comment by Horus645** [comment]
Sorry for the *very* late reply.

This is not something I have any interest in supporting. The daemon client-server architecture was chosen simply because it was the only way to have a wallpaper manager that did not have to be restarted to change the wallpaper.

Rykv is necessary to achieve a good level of performance with our current implementation. Without it, I do not see how we could match our current small memory footprint. Furthermore, the compression algorithm we are using is two handwritten functions in Rust, that I'd have to allow others to use in different languages.

As a workaround, maybe we could offer some of `swww` functionalities as a library, so you wouldn't have to spawn all those processes. Nevertheless, that would be a very long term goal :cry:

**Comment by LordMZTE** [comment]
I don't really see how the use of a serialization library such as Rykv is inherently faster than a hand-written serialization function. In fact, I believe that the opposite is the case. A manually written serialization function is almost certainly able to achieve better results than a general-purpose algorithm.

It's very much possible to implement what Rkyv does here (zero-copy) while also having a well-documented API. However, I don't even believe it's strictly necessary to avoid memory allocation for socket message serialization, keeping a copy of a few strings around for a few milliseconds isn't what causes large memory footprints.

About the compression, I'm not sure what exactly is going on here, I've not looked that far into swww's code. Using compression for a socket API doesn't really seem reasonable to me here, because it doesn't necessarily speed things up at all. It's extra CPU work to be done and offers little to no benefit when not communicating over a network.

As for your suggestion about offering this as a library (in Rust, I presume), this isn't really that useful. It'd be fairly trivial to re-implement this API in Rust. I could just write identical structs and use the Rkyv library. My point here was that the way the socket API currently works is extremely unfriendly to other languages which work fundamentally differently than Rust and thus are realistically incompatible with Rkyv. 
The only way I could imagine this working is to package this as a dynamically linked library alongside swww, with C headers. This would also have the added benefit of avoiding version conflicts, but I think that this is probably unreasonably complicated.

**Comment by Horus645** [comment]
I don't disagree that a handwritten serialization scheme could be better than Rykv. I simply do not want to do it myself. It is not as trivial a problem as you seem to be implying here.

> I don't even believe it's strictly necessary to avoid memory allocation for socket message serialization, keeping a copy of a few strings around for a few milliseconds isn't what causes large memory footprints

This is the problem. We need to serialize entire images, mostly with 1920 * 1080 ~= 2 million pixels. With 3 bytes per pixels, that is around 6MB. So we can't really store the whole thing twice. This means we need *some* form of zero-copy, otherwise our memory usage *will* go up. For reference, currently a 450 frame gif only takes up around 28MB on my machine, so 6MB is indeed a lot.

> About the compression, I'm not sure what exactly is going on here, I've not looked that far into swww's code. Using compression for a socket API doesn't really seem reasonable to me here, because it doesn't necessarily speed things up at all. It's extra CPU work to be done and offers little to no benefit when not communicating over a network.

This is not backed up by my previous benchmarks, reducing the memory we have to transfer over has led to a significant increase in performance. If we think about the gif I mentioned above, 450 frames of 1920 x 1080 pixels would give us around 6MB * 450 = 2.700GB. The compression scheme I am using is reducing that to like, a dozen MB or so. I don't think there is any way you can send nearly 200x more data and not have it impact performance, though I could be wrong.

Just to be clear, this compression algorithm is only used when we are animating gifs. When we send static images, we send them raw.

To summarize:
  - I agree that a handwritten serialization scheme could be better than what we currently use, but;
  - I have no interest in writing that, because:
    * it is non-trivial to achieve Rykv performance, both in raw CPU time and in memory usage
    * we would have to standardize our compression algorithm (which is actually not that difficult, but it IS more work) 
    * alternatively, I would like to have benchmarks showing that we can send the raw gifs to the daemon without a lot of memory and/or CPU overhead.

Finally, I don't think that having a wallpaper daemon with a generic protocol for sending in images is a bad idea at all! In fact, I would be more than willing to contribute to such a project. But, unfortunately, I do not believe I have any interest in implementing this in `swww`, at least not for the foreseeable future. It would involve a lot of extra work, and I am already struggling to deal with the problems arising from the current implementation.

**Comment by LGFae** [comment]
#299 actually implements a manual serialization scheme. I admit it wasn't as bad as I initially thought it would be.

Nevertheless, though it is theoretically possible to make an alternative client to `swww`, that use-case is still not supported. The serialized format may change without notice or warning (in fact, I wouldn't even mark it as a breaking change). Maybe one day we'll stabilize it somehow, but that day is still far off.

**Comment by LordMZTE** [comment]
Great! Thank you!
