### ISSUE TITLE
change name of clear arg to color

### ISSUE THREAD

**Issue by exoess** [LGFae/swww#194]
the name clear doesn't really make sense for just changing the background to a solid color, i recommend changing clear to making the background black, and having an arg color that requires a color after it and doesn't have a default

**Comment by flick0** [comment]
imo its just an alternative to clear to set solid colors with transitions and cache

**Comment by LGFae** [comment]
Ah, I see. Well, ok then. Let's go with it.

**Comment by hkupty** [comment]
Can I offer a different perspective? It could make sense to simplify here and take the same approach of grim + slurp. It might make sense to generate the bitmap/image in a separate process and pass it on to swww instead...

**Comment by LGFae** [comment]
Yeah, I think I like @hkupty's idea better. We can create the image straight in `swww` itself, consisting of one full static color. We get transitions and cache "for free".

That would actually even simplify some code in the daemon, because we could both `Clear` and `Image` requests into one.

The problem would only be how to cache it, because colors aren't associated with any filepath. But this should be easy: we store the image's fullpath in the cache right now, so all we have to do is:

  * if it's a file, store its fullpath
  * if it's a color, store its value, with a starting `#`.
  
Since no fullpath will ever start with `#` (as far as I know), we should be safe

**Comment by flick0** [comment]
That does sound like a better idea, i can update this pr to move the image stuff to swww

**Comment by flick0** [comment]
sorry im a bit late to this, but dont we already do the image gen in swww instead of daemon lol

**Comment by LGFae** [comment]
we do??? I mean, in master we have:

```rust 
        Swww::Clear(c) => {
            let (format, _, _) = get_format_dims_and_outputs(&[])?;
            let mut color = c.color;
            if format.must_swap_r_and_b_channels() {
                color.swap(0, 2);
            }
            let clear = ipc::ClearSend {
                color,
                outputs: split_cmdline_outputs(&c.outputs),
            };
            Ok(Some(RequestSend::Clear(clear.create_request())))
        }
```
So, right now we don't. Maybe in the PR you've already implemented.
