### ISSUE TITLE
Wallpaper show distorted and in grayscale

### ISSUE THREAD

**Issue by Hanazono-Yurine** [LGFae/swww#233]
Buenos Dias meus consagrados.

Today I performed a complete update on my system. Then I restarted my laptop.
But when the system start, my wallpaper was distorted and in grayscale.
I tried changing to another wallpaper, but it stayed the same, so I tried set to a random color with `swww clear a260f1`, but it stayed in grayscale.
I installed the `swww-git` package with yay.

Some info:

Screenshot
![screenshot-2024-03-16_17:09:42](https://github.com/LGFae/swww/assets/142830863/8405a310-8601-4d8f-a13c-349b11d11f57)

```
$ swww --version
swww 0.8.2-masterV2
```
The version on `pacman -Qi swww-git`, is the last commit of the main branch
```
0.4.0.r301.g0516ea0-1
```

```
$ swww query
eDP-1: 1366x768, scale: 1, currently displaying: image: /home/zoe/Pictures/Wallpapers_Desktop/Games/381583.jpg
```

I'm using Arch with the latest kernel version `6.7.9-arch1-1`
If you need more information, just let me know and I'll do my best to provide it.

**Comment by LGFae** [comment]
Can you try running `swww-daemon` manually in a different terminal, to see what `wl_shm format` it is using? I feel this might be a problem with that.

**Comment by Hanazono-Yurine** [comment]
I'm using hyprland, more specifically `hyprland-git`.
Version of hyprland if necessary:
```
$ hyprctl version
Hyprland, built from branch main at commit 0e87a08e15c023325b64920d9e1159f38a090695 dirty (renderer: disable surface adjustments for misaligned reported when manual resizing).
Date: Sat Mar 16 14:56:09 2024
Tag: v0.37.1-4-g0e87a08e

flags: (if any)
```
The output of `swww-daemon` :
```
$ swww-daemon
22:12:30 [INFO] (main) Initialization succeeded! Starting main loop...
22:12:30 [INFO] (main) Selected wl_shm format: Bgr888
```
And about my monitor setup, maybe I'm dumb, but I don't know if that's what you want, so I just copied my setup from hyprland
`monitor=,highres,auto,1`
I'm on my laptop, without any external monitor if that's what you wanted.

**Comment by LGFae** [comment]
Hm. I have been unable to reproduce this with the `hyprland-git`. Try the following:

```
swww kill # kill any currently running instance
swww clear-cache # delete the cache; it might be causing problems
swww init # init it again
swww img <your image> # set your image
```

If that doesn't work, I am afraid I am going to have to ask you to try installing the latest `swww`released version, to confirm if the issue also happens there.

**Comment by Hanazono-Yurine** [comment]
I ran the commands, but they didn't work.
Installing the `swww` package worked (version 0.8.2)

**Comment by LGFae** [comment]
Good, we've at least found a workaround. Nevertheless, we should try to solve this before the next release.

**Comment by LGFae** [comment]
Are you also on a laptop, by any chance?

**Comment by CaioSimioni** [comment]
Yes, Aspire A515-41G

**Comment by virinci** [comment]
Hi, I am also facing the same issue after updating sway. I am using Void Linux. https://github.com/void-linux/void-packages/commit/b796af39921a44081edbb5b0ddc9ff10756744bd is the commit that introduced this update.

I ran `git bisect` and it resulted in d67bb8bb17307398dba767ff22acaa96db2733ac as the first bad commit. I hope this helps. That's a hefty commit and I cannot make much sense of it. I will try to use the released version for now.

**Comment by LGFae** [comment]
Yeah, I figured that commit would be the most likely culprit. You having the problem on sway as well is a good indicator that I overlooked something.

What that commit is doing is essentially using a 3 channel color format (RBG) instead of the default 4 channel color format (RGBA). The 3 channel color format is not guaranteed to be supported by all compositors, so we still the 4 channel color format as a fallback. The fallback logic is why that commit looks so complicated, because now many functions need to work with both rgb and rgba.

**Comment by LGFae** [comment]
> However, what I don't understand is why I can't install swww.

Rust transformed that into an error in a newer version of the compiler. At the time I released 0.8.2, it wasn't an error.

**Comment by LGFae** [comment]
@virinci when you say you updated say, are you on sway version 1.9? Cause I just tested that with my notebook and I couldn't reproduce this issue...

**Comment by LGFae** [comment]
Everyone, could someone please test PR #235 and try using the `swww-daemon` with

```
swww-daemon --format xrgb
```

See if it serves as a workaround.

**Comment by skinnypuppy** [comment]
Can confirm that swww-daemon --format xrgb works properly now on my laptop. Just downloaded the main branch, did a checkout of option-to-force-wayland_shm_format and wallpaper displays correctly and in color.  Vanilla Arch, hyprland, kernel 6.8.1

**Comment by Hanazono-Yurine** [comment]
I can also confirm that PR #235 works

**Comment by mido-dev1** [comment]
hi, i also have the same problem after update swww to 0.9.1
but with `swww-daemon --format xrgb` it works fine

**Comment by LGFae** [comment]
This really seems like `wlr-roots` is just reporting shm formats that aren't actually supported. Grayscale and tilted images are more or less what I'd expect if we are trying to display an rgb image in an rgba surface. The fact this only happens on laptops integrated displays further corroborates this. I've tried looking over `wlr-roots` issue tracker and code to see if I could find anything obvious, but I suppose the `wlr-roots` devs wouldn't make any obvious mistakes I would be able to find easily.

Ideally, to confirm this, I'd have to be able to reproduce this bug using a bgr888 surface in `tinywm`, the barebones window manager `wlr-roots` uses as an example. On the other hand, if it *works* in `tinywm`, then we could be sure that the problem is probably with us, somehow.

**Comment by L4FeeR** [comment]
> I ran the commands, but they didn't work. Installing the `swww` package worked (version 0.8.2)

How to install that version? I have latest version currently

**Comment by LGFae** [comment]
@L4FeeR try using `swww-daemon --format xrgb` instead. That workaround seems to be working for everyone.

**Comment by L4FeeR** [comment]
Yeah working for me, but how to set it to start at boot? And will it work
after change wallpaper?

**Comment by edbanshee** [comment]
I have the exact same issue. Arch LTS, Hyprland, with Stephan Raabe dotfiles, started since the last update. Dual monitor configuration with a laptop:
```
monitor=eDP-1,1366x768,1920x720,1
monitor=HDMI-A-1,1920x1080,0x0,1
```

However I noticed that if I change my native laptop resolution, and use this configuration instead, the issue is gone after rebooting:
```
monitor=eDP-1,1920x1080,1920x720,1
monitor=HDMI-A-1,highres,0x0,1

```
Which leads me to believe its not only an issue pertaining laptop integrated screen, but also native 1366x768 resolution. 

Im not sure I understand the workarounds, tried to uninstall swww and install both latest release and git separately. `swww-daemon` brings me this:
`Error: "couldn't bind socket: Address already in use (os error 98)"`

Can only assume thats an error due to the configuration of the dotfiles as a whole.

Regardless, the swww wallpaper distortion and grayscale is part of the latest release.

**Comment by LGFae** [comment]
You cannot have more than 1 daemon running at the same time. If you have any other instances of `swww-daemon` running, you must run first `swww kill` them to stop them.

The workaround is simply starting the daemon with the command `swww-daemon --formst xrgb`. This issue is only caused when the wayland's buffer's format is in bgr in some integrated displays.

In any case, I appreciate the new data point that the resolution seems to matter!

**Comment by coacharnold1** [comment]
Hi Folks ,   running Fedora 40 - Beta here ...  when I run _swww kill_ and then   _swww-daemon --format xrgb_  I get this 

thread 'main' panicked at daemon/src/main.rs:129:45:
failed to connect to the wayland server: NoCompositor
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
22:47:49 [INFO] (main) Removed socket at "/run/user/1000/swww.socket"

**Comment by cariosa** [comment]
Same issue, but when I first booted and changed wallpaper (in hyprland with hyprdots) it crashed and logged out of session. now it's working fine with the workaround.

**Comment by GinoongFlores** [comment]
> Hi Folks , running Fedora 40 - Beta here ... when I run _swww kill_ and then _swww-daemon --format xrgb_ I get this
> 
> thread 'main' panicked at daemon/src/main.rs:129:45: failed to connect to the wayland server: NoCompositor note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace 22:47:49 [INFO] (main) Removed socket at "/run/user/1000/swww.socket"

On fedora, upon asking on their dc, someone said that you can add this line to your `Startup_Apps.conf`  
add this line `--format xrgb`  => `exec-once = swww query || swww init --format xrgb`

**Comment by infopcgood** [comment]
Same issue here. Arch Linux, updated at 2024. 04. 03 11:00 KST(UTC+09:00). Using version `0.9.1-1` on AUR.

**Comment by LGFae** [comment]
Well, yeah, for sure. The issue is we only use `bgr` when the compositor tell us it is supported. There's apparently another check I need to do besides that, but I don't know what it is (doesn't help that I haven't been able to reproduce this, even using different resolutions like @edbanshee reported).

**Comment by LGFae** [comment]
Hello everyone, could someone in here test out PR #266 to see if this problem is fixed? While doing that large refactor, I think I may have come across something that could have caused this problem.

**Comment by Hanazono-Yurine** [comment]
Opa meu rei.

I cloned and compiled PR #266
But running the `swww-daemon` still has the same bug.

Log if needed:
```
12:10:23 [DEBUG] (main) swww_daemon: Made socket in "/run/user/1000/swww.socket" (pathname) and initialized logger. Starting daemon...
12:10:23 [INFO] (main) Selected wl_shm format: Bgr888
12:10:23 [DEBUG] (main) swww_daemon: New output: wl_output@6
12:10:23 [INFO] (main) Initialization succeeded! Starting main loop...
12:10:23 [DEBUG] (main) swww_daemon: output wl_output@6 position: 0,0
12:10:23 [DEBUG] (main) swww_daemon::wallpaper: Output wl_output@6 name: eDP-1
12:10:23 [DEBUG] (main) swww_daemon::wallpaper: Output wl_output@6 description: AU Optronics 0x81EC (eDP-1)
12:10:23 [WARN] (main) Received transform. We currently ignore those
12:10:23 [DEBUG] (transition) swww_daemon::wallpaper: output Some("AU Optronics 0x81EC (eDP-1)") - drawing: image: /home/jeffersonCaminhoes/Pictures/Wallpapers_Desktop/Arts/396621.jpg
12:10:23 [DEBUG] (transition) swww_daemon::animations::transitions: Starting transitions
12:10:23 [INFO] (transition) BumpPool with: 1 buffers. Size: 3073Kb
12:10:23 [INFO] (transition) BumpPool with: 2 buffers. Size: 6147Kb
12:10:23 [DEBUG] (transition) swww_daemon::wallpaper: waiting for condvar
12:10:23 [DEBUG] (main) swww_daemon: Output wl_output@6: Surface Enter
12:10:23 [DEBUG] (transition) swww_daemon::animations::transitions: Transitions finished
12:10:26 [DEBUG] (transition) swww_daemon::wallpaper: output Some("AU Optronics 0x81EC (eDP-1)") - drawing: image: /home/jeffersonCaminhoes/Pictures/Wallpapers_Desktop/Games/zelda-link-3840-x-2160-v0-l4evnhj06uvb1.jpg
12:10:26 [DEBUG] (transition) swww_daemon::animations::transitions: Starting transitions
12:10:29 [DEBUG] (transition) swww_daemon::wallpaper: waiting for condvar
12:10:29 [DEBUG] (transition) swww_daemon::wallpaper: waiting for condvar
12:10:29 [DEBUG] (transition) swww_daemon::wallpaper: waiting for condvar
12:10:29 [DEBUG] (transition) swww_daemon::wallpaper: waiting for condvar
12:10:29 [DEBUG] (transition) swww_daemon::wallpaper: waiting for condvar
12:10:29 [DEBUG] (transition) swww_daemon::wallpaper: waiting for condvar
12:10:29 [DEBUG] (transition) swww_daemon::animations::transitions: Transitions finished
```
