### ISSUE TITLE
Bug when use Vertical Monitor after updating to hyprland 0.44.0

### ISSUE THREAD

**Issue by Jax-Tsai-zero** [LGFae/swww#367]
![image](https://github.com/user-attachments/assets/552bfcfb-9a57-4324-ae35-1b9c1ad2fd51)

**Comment by SleepyZzed** [comment]
Also facing this issue since updating

**Comment by anekos** [comment]
I experienced the same issue, but it appears to have been potentially fixed in the latest commit. 

Here are screenshots showing the results with the latest release 0.9.5 and the most recent git commit:

![screenshot-2024-10-09-07-38-01](https://github.com/user-attachments/assets/1559d1da-f5a8-4357-8266-7d2f678aaa32)
Latest release 0.9.5

![screenshot-2024-10-09-07-40-07](https://github.com/user-attachments/assets/9322f64e-a5f4-4355-a5c2-e65c1b48b8f0)
Latest git commit



As you can see, the vertical monitor display issue seems to be resolved in the latest commit.
